models:
  image: tp33/django
  external_links:
    -  mysql:db
  volumes:
    - .:/app
  ports:
    - "8001:8000"
  command: bash -c "pip install requests && python ./getlearnt/manage.py makemigrations marketplace && python ./getlearnt/manage.py migrate marketplace && python ./getlearnt/manage.py loaddata ./getlearnt/db.json && mod_wsgi-express start-server --working-directory getlearnt --reload-on-changes ./getlearnt/getlearnt/wsgi.py"

exp:
  image: tp33/django
  links:
    - models:models-api
    - es:es
    - kafka:kafka
  ports:
    - "8002:8000"
  volumes:
    - .:/app
  command: bash -c "pip install requests && mod_wsgi-express start-server --working-directory /app/exp --reload-on-changes /app/exp/exp/wsgi.py"

web:
  image: tp33/django
  links:
    - exp:exp-api
    - redis:redis
  ports:
    - "8000:8000"
  volumes:
    - .:/app
  command: bash -c "pip install requests && pip install redis && python ./ui/manage.py collectstatic --noinput && mod_wsgi-express start-server --working-directory /app/ui --reload-on-changes /app/ui/ui/wsgi.py"

web2:
  image: tp33/django
  links:
    - exp:exp-api
    - redis:redis
  ports:
    - "8010:8000"
  volumes:
    - .:/app
  command: bash -c "pip install requests && pip install redis && python ./ui/manage.py collectstatic --noinput && mod_wsgi-express start-server --working-directory /app/ui --reload-on-changes /app/ui/ui/wsgi.py"

web3:
  image: tp33/django
  links:
    - exp:exp-api
    - redis:redis
  ports:
    - "8020:8000"
  volumes:
    - .:/app
  command: bash -c "pip install requests && pip install redis && python ./ui/manage.py collectstatic --noinput && mod_wsgi-express start-server --working-directory /app/ui --reload-on-changes /app/ui/ui/wsgi.py"



kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   volumes:
      - .:/app
   command: bash -c "python ./batch/batch.py"

batch2:
   image: tp33/django
   container_name: batch2
   links:
      - kafka:kafka
   volumes:
      - .:/app
   command: bash -c "python ./batch/click_batch.py"

redis:
  image: library/redis
  container_name: redis
  ports:
    - "6379:6379"

selenium-chrome:
  image: selenium/standalone-chrome
  container_name: selenium-chrome
  links:
    - web:web
  ports:
    - "4444:4444"

selenium-test:
  image: tp33/django
  container_name: selenium-test
  links:
    - selenium-chrome:selenium-chrome
    - web:web
  volumes:
    - ./app/selenium:/app
  command: bash -c "pip install selenium && python integration-tests.py && python forever.py"

haproxy:
  image: my-haproxy
  container_name: haproxy
  links:
    - web:web
    - web2:web2
    - web3:web3
  ports:
    - "8181:80"


spark-master:
  image: gettyimages/spark
  external_links:
    - mysql:db
  command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  container_name: spark-master
  hostname: spark-master
  environment:
    MASTER: spark://spark-master:7077
    SPARK_CONF_DIR: /conf
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./data:/tmp/data

spark-worker:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  container_name: spark-worker
  hostname: spark-worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 512m
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - spark-master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./data:/tmp/data
